--- 
title: "Supplementary data for paper: A pilot study of linear metrics for previously-defined type-varieties of Gary dart points"
author: "Robert Z. Selden, Jr."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This pilot study is focused upon the analysis of linear metrics for whole/intact specimens of Gary dart points from the Poverty Point, Cooper, and Means sites in advance of a geometric morphometric study."
---

# Preface {-}

>Reproducibility—the ability to recompute results—and replicability—the chances other experimenters will achieve a consistent result—are two foundational characteristics of successful scientific research [@RN20918].

This volume is written in **Markdown**, and includes all analysis code employed in the study, providing a means for others to reproduce (exactly) those results discussed and expounded upon in the following chapters. The reproducible nature of this undertaking provides a means for others to critically assess and evaluate the various analytical components of this study [@RN20915;@RN20916;@RN20917], which is a necessary requirement for the production of reliable knowledge. Typology is the topic of this particular undertaking, and typological assignments often provide the requisite foundation for many of the assumptions, inferences, and interpretations that archaeologists regularly make. Diagnostic types---whether functional, decorative, morphological, or chronological [@RN20847]---are of considerable import in formulating archaeological interpretations. There has been no shortage of studies related to discussion of interobserver error in the assignment of archaeological types [@RN20922;@RN20921;@RN20920;@RN20919], and while the lack of consistency in the application of types among investigators is recognized as problematic, it is expected that the lack of consistency may be even more pronounced at the level of the type-variety.

Diagnostic artifact types provide the analytical foundation upon which much of our knowledge of the past is based. The focus of this particular study lies one level of abstraction beneath that of the type, on the many previously-defined type-varieties for Gary dart points. Given the ubiquity of Gary dart points, and the wide range of morphological variability in the type, it is not at all surprising that in at least one instance, a type-variety (_var. Beaver Tail Stem_) [@RN20895, 12-18] was posited seven years before the formal definition of the Gary dart point was advanced [@RN5066].

This exploratory study of linear metrics includes those Gary dart point type-varieties advanced at the Poverty Point, Cooper, and Means sites, providing the requisite analytical foundation needed to outline a basic archaeological epistemology for the Gary type. Further work will be needed to expand upon this study, which provides a basic data-driven approach to assigning the previously-posited type-varities. This effort does not delve into the various _**sub-type-varieties**_ (i.e., _Camden subgroup A_, _Camden subgroup B_), as it it focused only upon those type-varieties that are no more than one level of abstraction below that of the Gary dart point. A subsequent geometric morphometric study will aid in testing those hypotheses advanced by this exploratory study, while others will require additional data collection to include those Gary dart points from the George C. Davis (TX), Jaketown (MS), Miller (TX), Yarbrough (TX), Lake George (MS), and Scott (OK) sites.

## Acknowledgments

I extend my gratitude to the Poverty Point World Heritage Site, and The University Museum in the J. William Fulbright College of Arts and Sciences at the University of Arkansas. Personal thanks go to Diana Greenlee and Mary C. Suter for their help and guidance regarding permissions and access to the collections. Additional thanks to Jared S. Pebworth and Ernest Gann for their assistance aggregating the Gary dart points from the collections, and with locating and sorting through the various associated site records from the Cooper and Means sites.

This volume enlists a variety of tools from the [Open Review Toolkit](https://www.openreviewtoolkit.org/), and some of the code provided for bookdown following in the steps of [Ben Marwick](https://benmarwick.github.io/bookdown-ort/). I extend my gratitude to all who contribute comments and constructive criticisms throughout the development and maturation of this project.

## Funding

Funding for this project was provided to RZS by the United States Forest Service, National Forests and Grasslands in Texas (15-PA-11081300-033 and 20-PA-11081300-074), and components of the analytical work flow were developed and funded by a Preservation Technology and Training grant (P14AP00138) to RZS from the National Center for Preservation Technology and Training.

## Privacy and Consent Policy

### Overview

The complete text of the supplementary data is made available on this website at no cost. While you are reading the volume, reader behavior is measured in aggregate. For example, which sections of the book get read most often is measured. These data will help to improve the book.

### What information do we collect?

[Google Analytics](https://analytics.google.com/) is used to collect information about how you interact with this website. Further, like most websites, [cookies](https://en.wikipedia.org/wiki/HTTP_cookie) are used to enhance your experience, gather general visitor information, and track visits to the website. Please refer to the "do we use cookies?" section below for information about cookies and how we use them.

### How do we use your information?

Any of the information that we collect may be used for research, to improve the supplementary data.

### How do we protect your information?

A variety of security measures is used to maintain the safety of the information that you provide.

Most of the browsing information that we gather is stored in Google Analytics, and you can read more about their [security and privacy principles](https://support.google.com/analytics/answer/6004245?hl=en).

Annotations that you can add are managed by [hypothes.is](https://hypothes.is/), and you can read more about their [terms of service](https://hypothes.is/terms-of-service/).

Our website is hosted by [Github Pages](https://pages.github.com/), and you can read more about Github's [terms of service](https://help.github.com/articles/github-terms-of-service/).

### Do we use cookies?

Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information.

In order to offer you a better site experience, cookies are used to understand and save your preferences for future visits, and to compile aggregate data regarding site traffic.

### Your consent

By using this site, you consent to the privacy policy.

### Questions

If you have any questions, please send us an email `bmarwick@uw.edu`

### Changes to our Privacy and Consent Policy

I reserve the right to this privacy policy from time to time at my discretion. Please periodically check this section to review the current version of the Privacy and Consent Policy. All previous policies are included in the associated repository, and this page will be updated if any changes are needed.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
